version: "3.9"
services:
  upstream:
    image: citizenstig/httpbin
    restart: always

  gateway:
    image: ${REGISTRY}/${GW_IMAGE}
    env_file:
      - ../configsets/${CONFIGSET}/gw.env
    ports:
      - "8080:8080"
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]

networks:
  default:
    name: tyk-network
    external: true