version: "3.9"
services:
  tyk-mdcb:
    volumes:
      - ${CONFIG_FOLDER}/${CONFIG}:/conf
  tyk-gateway-datacenter-1-alfa:
    volumes:
      - ${CONFIG_FOLDER}/${CONFIG}:/conf
      - ${VOLUME_FOLDER}/gw/certs:/etc/ssl/certs
  tyk-gateway-datacenter-2-alfa:
    volumes:
      - ${CONFIG_FOLDER}/${CONFIG}:/conf
      - ${VOLUME_FOLDER}/gw/certs:/etc/ssl/certs
  tyk-gateway-datacenter-1-beta:
    volumes:
      - ${CONFIG_FOLDER}/${CONFIG}:/conf
      - ${VOLUME_FOLDER}/gw/certs:/etc/ssl/certs
  tyk-gateway-datacenter-2-beta:
    volumes:
      - ${CONFIG_FOLDER}/${CONFIG}:/conf
      - ${VOLUME_FOLDER}/gw/certs:/etc/ssl/certs