version: "3.9"
services:
  upstream:
    container_name: httpbin.org
    image: kennethreitz/httpbin
    restart: always

  gateway:
    container_name: gateway
    image: ${REGISTRY}/${GW_IMAGE}
    env_file:
      - ../configsets/${CONFIGSET}/gw.env
    ports:
      - "6000:6000"
      - "8003:8003"
      - "8080:8080" 
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]

  dashboard:
    container_name: dashboard
    image: ${REGISTRY}/${DB_IMAGE}
    ports:
      - "3000:3000"
      - "5000:5000"
      - "1026:1025"
    env_file:
      - ../configsets/${CONFIGSET}/dash.env
    entrypoint: ["/opt/tyk-dashboard/tyk-analytics", "--conf", "/conf/tyk-analytics.conf"]

  tyk-pump:
      container_name: tyk-pump
      image: ${REGISTRY}/${PUMP_IMAGE}
      env_file:
        - ../configsets/${CONFIGSET}/pump.env
      ports:    
          - "8061:8061"
  bundle-server:
      container_name: bundle-server
      build:
        context: ./bundle_server
      ports:
          - "8000:8000"
  federation-server:
      container_name: federation
      image: agatawitkowska/federation-example
      ports:
          - "4000:4000"
          - "4001:4001"
          - "4002:4002"
          - "4003:4003"
  openldap:
      image: osixia/openldap:1.5.0
      container_name: openldap
      ports:
      - '389:389'
      - '636:636'
      environment:
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=read-only-admin
      - LDAP_READONLY_USER_PASSWORD=password
  graphql-faker:
      container_name: graphql-faker
      image: apisguru/graphql-faker:latest
      command: "faker-schema.graphql"
      ports:
          - "9002:9002"
  test:
    container_name: test
    image: ${REGISTRY}/${TEST_IMAGE}
    env_file:
      - ../configsets/${CONFIGSET}/test.env

networks:
  default:
    name: tyk-network
    external: true