x-aws-vpc: ${AWS_VPC}

services:
  gateway:
    environment:
      - TYK_GW_STORAGE_HOST=redis.${COMPOSE_PROJECT_NAME}-dependencies.local
    entrypoint: []

networks:
  default:
    name: tyk-network
    external: false