version: "3.9"
services:
  tyk-gateway:
    volumes:
      - ${CONFIG_FOLDER}/${CONFIG}:/conf
      - ${VOLUME_FOLDER}/gw/certs:/etc/ssl/certs
      # - ./conf/tyk_pro.conf:/opt/tyk-gateway/tyk.conf
      # - ./conf/tyk_pro.conf:/develop/confs/tyk.conf
      # - ${CONFIG_FOLDER}/${CONFIG}:/develop/confs
      # - ${VOLUME_FOLDER}/gw/tyk-gateway/middleware:/opt/tyk-gateway/middleware
      # - ${VOLUME_FOLDER}/gw/tyk-gateway/apps:/opt/tyk-gateway/apps
      # - ${VOLUME_FOLDER}/gw/tyk-gateway/templates:/opt/tyk-gateway/templates
      # - ${GOPATH}:/develop/go
      # - ./apps:/opt/tyk-gateway/apps
  tyk-dashboard:
    volumes:
      - ${CONFIG_FOLDER}/${CONFIG}:/conf
      # - ./conf/tyk_analytics.conf:/opt/tyk-dashboard/tyk_analytics.conf
      # - ${DASH_REPO_PATH}:/develop/go/src

  tyk-pump:
    volumes:
      - ${CONFIG_FOLDER}/${CONFIG}:/conf
  test:
    volumes:
      - ${VOLUME_FOLDER}/test:/app/test-data