version: "3.9"
services:
  upstream:
    image: citizenstig/httpbin
    restart: always

  gateway:
    image: ${REGISTRY}/${GW_IMAGE}
    ports:
      - "8080:8080"
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]

x-aws-cloudformation:
  Resources:
    LoadBalancer:
      Properties:
        Subnets:
        - subnet-06ab6f58bb6d23123   #Public-1a
        - subnet-0bbe276402b376013   #Public-1b
        # - subnet-04d34f3e5863af20a #Private-1a

networks:
  default:
    name: tyk-network
    external: true