AWSTemplateFormatVersion: 2010-09-09
Description: Secret generation for tyk installation

Parameters:
  TYKDBAdminUserName:
    Description: TYK DASHBOARD ADMIN USERNAME
    Type: String
    Default: ""
  PumpDbAdminUser: #Name of the Mongo Admin Password
    Description: MongoDb Pump User Name
    Type: String
    Default: ""
  MongoAdminUsername: #Name of the Mongo Admin Username
    Description: MongoDb Admin Username
    Type: String
    Default: "clusteradmin"
  

Resources:

  SharedNodeSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This the shared node secret
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
        ExcludePunctuation: true

  GWDashboardSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This the shared node secret
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
        ExcludePunctuation: true

  AdminSecretDashboard:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This the shared node secret
      GenerateSecretString:
        SecretStringTemplate: '{}'
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
        ExcludePunctuation: true

  TYKDBAdminCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This the Tyk DB admin password
      GenerateSecretString:
        SecretStringTemplate: !Sub ['{"username": "${admin}"}', admin: !Ref TYKDBAdminUserName ]
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
        ExcludePunctuation: true

  PumpDbAdminCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This the MongoDb Pump Admin User Credentials
      GenerateSecretString:
        SecretStringTemplate: !Sub ['{"username": "${admin}"}', admin: !Ref PumpDbAdminUser ]
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
        ExcludePunctuation: true

  MongoAdminCredentials:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: This the MongoDb Admin User Credentials
      GenerateSecretString:
        SecretStringTemplate: !Sub ['{"username": "${admin}"}', admin: !Ref MongoAdminUsername ]
        GenerateStringKey: password
        PasswordLength: 16
        ExcludeCharacters: "\"@/\\"
        ExcludePunctuation: true

Outputs:
  SharedNodeSecretArn:
    Description: "The shared node aws managed secret arn"
    Value: !Ref SharedNodeSecret
  GWDashboardSecretArn:
    Description: "The Gw dashboard aws managed secret arn"
    Value: !Ref GWDashboardSecret
  AdminDashboardSecretArn:
    Description: "The admin dashboard managed secret arn"
    Value: !Ref AdminSecretDashboard
  TYKDBAdminCredentialsArn:
    Description: "The DB admin dashboard managed secret arn"
    Value: !Ref TYKDBAdminCredentials
  PumpDbAdminCredentialsArn:
    Description: "The DB admin pump managed secret arn"
    Value: !Ref PumpDbAdminCredentials
  MongoAdminCredentialsArn:
    Description: "The Mongo DB admin managed secret arn"
    Value: !Ref MongoAdminCredentials  
