services:
  bundle-server:
    profiles: ["all", "master-datacenter"]
    container_name: bundle-server
    build:
      context: ./bundle-server
    ports:
      - "8000:8000"

  federation-server:
    profiles: ["all", "master-datacenter"]
    container_name: federation
    image: agatawitkowska/federation-example
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"

  openldap:
    profiles: ["all", "master-datacenter"]
    container_name: openldap
    image: osixia/openldap:1.5.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=read-only-admin
      - LDAP_READONLY_USER_PASSWORD=password

  graphql-faker:
    profiles: ["all", "master-datacenter"]
    container_name: graphql-faker
    image: apisguru/graphql-faker:latest
    volumes:
      - ./faker-schema.graphql:/workdir/faker-schema.graphql
    command: "faker-schema.graphql"
    ports:
      - "9002:9002"

  upstream:
    profiles: ["all", "master-datacenter"]
    container_name: httpbin.org
    image: kennethreitz/httpbin
    restart: always

  restcountries:
    profiles: ["all", "master-datacenter"]
    container_name: restcountries
    image: bigpapoo/restcountries:1.0

  trevorblades:
    profiles: ["all", "master-datacenter"]
    container_name: trevorblades
    image: mangomm/trevorblades-countries

  webhook:
    profiles: ["all", "master-datacenter"]
    container_name: webhook-server
    build:
      context: ./webhook-server
    ports:
      - "9003:9003"

  nginx:
    profiles: ["all", "master-datacenter"]
    container_name: nginx
    image: nginx:latest
    ports:
      - "7000:80"
      - "7443:443"
    volumes:
      - ./confs/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./certs/nginx.key:/etc/nginx/ssl/nginx.key
    depends_on:
      - upstream

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
      - "9094:9094"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_METADATA_LOG_DIR: /var/lib/kafka/data
      KAFKA_LOG_DIRS: /var/lib/kafka/data

  rabbitmq:
    profiles: ["all", "master-datacenter"]
    container_name: rabbitmq
    image: rabbitmq:4.1.0-management-alpine
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
      - "1883:1883"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    command: sh -c "rabbitmq-plugins enable --offline rabbitmq_mqtt && rabbitmq-server"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 3

  grpc-server:
    profiles: ["all", "master-datacenter"]
    container_name: grpc-server
    image: tykio/tyk-grpc-plugin:v1.0
    ports:
      - "9111:9111"

  keycloak:
    profiles: ["all", "master-datacenter"]
    container_name: keycloak
    image: quay.io/keycloak/keycloak:23.0
    command: ["start-dev", "--import-realm", "--health-enabled=true"]
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/tyk-test-realm.json:/opt/keycloak/data/import/tyk-test-realm.json:ro
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/8080 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\n\\r\\n' >&3 && cat <&3 | grep -q UP"]
      interval: 10s
      timeout: 10s
      retries: 15
      start_period: 30s

  mcp-server:
    profiles: ["all", "master-datacenter"]
    container_name: mcp-server
    # Built from: https://github.com/TykTechnologies/tyk-mock-mcp-server
    # Dockerfile: https://github.com/TykTechnologies/tyk-mock-mcp-server/blob/main/Dockerfile
    image: 754489498669.dkr.ecr.eu-central-1.amazonaws.com/tyk-mock-mcp-server:main
    ports:
      - "7878:7878"
    environment:
      - PORT=7878
      - DEBUG=false
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7878/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
