version: "3.9"
services:
  bundle-server:
    profiles: ["all", "master-datacenter"]
    container_name: bundle-server
    build:
      context: ./bundle-server
    ports:
      - "8000:8000"

  federation-server:
    profiles: ["all", "master-datacenter"]
    container_name: federation
    image: agatawitkowska/federation-example
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"

  openldap:
    profiles: ["all", "master-datacenter"]
    container_name: openldap
    image: osixia/openldap:1.5.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=read-only-admin
      - LDAP_READONLY_USER_PASSWORD=password

  graphql-faker:
    profiles: ["all", "master-datacenter"]
    container_name: graphql-faker
    image: apisguru/graphql-faker:latest
    volumes:
      - ./faker-schema.graphql:/workdir/faker-schema.graphql
    command: "faker-schema.graphql"
    ports:
      - "9002:9002"

  upstream:
    profiles: ["all", "master-datacenter"]
    container_name: httpbin.org
    image: kennethreitz/httpbin
    restart: always

  restcountries:
    profiles: ["all", "master-datacenter"]
    container_name: restcountries
    image: bigpapoo/restcountries:1.0

  trevorblades:
    profiles: ["all", "master-datacenter"]
    container_name: trevorblades
    image: mangomm/trevorblades-countries

  webhook:
    profiles: ["all", "master-datacenter"]
    container_name: webhook-server
    build:
      context: ./webhook-server
    ports:
      - "9003:9003"

  nginx:
    profiles: ["all", "master-datacenter"]
    container_name: nginx
    image: nginx:latest
    ports:
      - "7000:80"
      - "7443:443"
    volumes:
      - ./confs/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/nginx.crt:/etc/nginx/ssl/nginx.crt
      - ./certs/nginx.key:/etc/nginx/ssl/nginx.key
    depends_on:
      - upstream

  grpc-server:
    profiles: ["all", "master-datacenter"]
    container_name: grpc-server
    image: tykio/tyk-grpc-plugin:v1.0
    ports:
      - "9111:9111"

  mcp-server:
    profiles: ["all", "master-datacenter"]
    container_name: mcp-server
    # Built from: https://github.com/TykTechnologies/tyk-mock-mcp-server
    # Dockerfile: https://github.com/TykTechnologies/tyk-mock-mcp-server/blob/main/Dockerfile
    image: 754489498669.dkr.ecr.eu-central-1.amazonaws.com/tyk-mock-mcp-server:v1.0.0
    ports:
      - "7878:7878"
    environment:
      - PORT=7878
      - DEBUG=false
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7878/health"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s
