version: "3"
services:
  valkey:
    profiles: ["all", "master-datacenter"]
    container_name: redis
    image: valkey/valkey:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "valkey-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  valkey-datacenter-1:
    profiles: ["all", "slave-datacenter"]
    container_name: redis-datacenter-1
    image: valkey/valkey:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6381:6379"
    healthcheck:
      test: [ "CMD", "valkey-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  valkey-datacenter-2:
    profiles: ["all", "slave-datacenter"]
    container_name: redis-datacenter-2
    image: valkey/valkey:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6382:6379"
    healthcheck:
      test: [ "CMD", "valkey-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  valkey-datacenter-3:
    profiles: ["all", "slave-datacenter"]
    container_name: redis-datacenter-3
    image: valkey/valkey:7.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6383:6379"
    healthcheck:
      test: [ "CMD", "valkey-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  wait_valkey:
    profiles: ["all", "master-datacenter"]
    image: hello-world:linux
    depends_on:
        valkey:
            condition: service_healthy

  wait_valkey_slaves:
    profiles: ["all", "slave-datacenter"]
    image: hello-world:linux
    depends_on:
        valkey-datacenter-1:
            condition: service_healthy
        valkey-datacenter-2:
            condition: service_healthy
        valkey-datacenter-3:
            condition: service_healthy