version: "3.9"
services:
  upstream:
    image: citizenstig/httpbin
    restart: always

  gateway:
    image: ${REGISTRY}/${GW_IMAGE}
    ports:
      - "8080:8080"
    environment:
      - TYK_GW_STORAGE_HOST=redis.oss-ecs-remote-external.local
    # volumes:
    #   - ../confs/${CONFIG}:/conf
    # entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]

networks:
  default:
    name: tyk-network
    external: true