version: "3.9"
services:
  upstream:
    image: citizenstig/httpbin
    networks:
      - internal-components
    restart: always

  gateway:
    image: ${REGISTRY}/${GW_IMAGE}
    ports:
      - "8080:8080"
    environment:
      - TYK_GW_STORAGE_HOST=redis
    # volumes:
    #   - ../confs/${CONFIG}:/conf
    depends_on:
      - redis
    # entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]
    networks:
      - external-components
      - internal-components

  redis:
    image: ${REDIS_IMAGE}
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s
    networks:
      - external-components
      - internal-components

  mongo:
    image: ${MONGO_IMAGE}
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - external-components
      - internal-components

networks:
  internal-components: 
    external: true
  external-components:
    external: true