x-aws-vpc: ${AWS_VPC}
x-aws-cluster: ${AWS_ECS_CLUSTER}
# x-aws-loadbalancer: "LoadBalancerName"

services:
  gateway:
    entrypoint: []

# services:
#   gateway:
#     volumes: []

# volumes:
#   gwconf:
#     external: true
#     name: "fs-6f33aa37"

# Use cloudformation Overlay to fix generated template
x-aws-cloudformation:
  Resources:
    LoadBalancer:
      Properties:
        Subnets:
        - subnet-064f338cc9de35c83 #prod-public-eu-central-1c
        - subnet-03685425d2c6f4ca9 #prod-public-eu-central-1b
        - subnet-02b27863f3c34175b #prod-public-eu-central-1a
    GatewayService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-02b27863f3c34175b #prod-public-eu-central-1a
    UpstreamService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-02b27863f3c34175b #prod-public-eu-central-1a
    MongoService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-03685425d2c6f4ca9 #prod-public-eu-central-1b
    RedisService:
      Properties:
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets:
              - subnet-03685425d2c6f4ca9 #prod-public-eu-central-1b

networks:
  internal-components: {}
  external-components: {}

# networks:
#   private:
#     external: true
#     name: "sg-0b69c799431fe3c61"
#   public:
#     external: true
#     name: "sg-0c76f7ba8cb5478ee"