apiVersion: v1
kind: ConfigMap
metadata:
  name: toxiproxy-config
  namespace: tyk
data:
  proxies.json: |
    [
      {
        "name": "dashboard",
        "listen": "[::]:3000",
        "upstream": "dashboard-svc-tyk-control-plane-tyk-dashboard.tyk.svc:3000",
        "enabled": true
      },
      {
        "name": "cp-gateway",
        "listen": "[::]:8080",
        "upstream": "gateway-svc-tyk-control-plane-tyk-gateway.tyk.svc:8080",
        "enabled": true
      },
      {
        "name": "dp-gateway",
        "listen": "[::]:8081",
        "upstream": "gateway-svc-tyk-data-plane-tyk-gateway.tyk-dp.svc:8080",
        "enabled": true
      },
      {
        "name": "mdcb",
        "listen": "[::]:9091",
        "upstream": "mdcb-svc-tyk-control-plane-tyk-mdcb.tyk.svc:9091",
        "enabled": true
      },
      {
        "name": "redis-cp",
        "listen": "[::]:6379",
        "upstream": "redis.tyk.svc:6379",
        "enabled": true
      },
      {
        "name": "redis-dp",
        "listen": "[::]:8379",
        "upstream": "redis.tyk-dp.svc:6379",
        "enabled": true
      },
      {
        "name": "mongo",
        "listen": "[::]:27017",
        "upstream": "mongo.tyk.svc:27017",
        "enabled": true
      }
    ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: toxiproxy
  namespace: tyk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toxiproxy
  template:
    metadata:
      labels:
        app: toxiproxy
    spec:
      containers:
      - name: toxiproxy
        image: ghcr.io/shopify/toxiproxy:2.5.0
        args:
        - "-host=0.0.0.0"
        - "-config=/etc/toxiproxy/proxies.json"
        ports:
        - containerPort: 3000
          name: dashboard
        - containerPort: 8080
          name: cp-gateway
        - containerPort: 8081
          name: dp-gateway
        - containerPort: 9091
          name: mdcb
        - containerPort: 6379
          name: redis-cp
        - containerPort: 8379
          name: redis-dp
        - containerPort: 27017
          name: mongo
        - containerPort: 8474
          name: api
        volumeMounts:
        - name: config-volume
          mountPath: /etc/toxiproxy
      volumes:
      - name: config-volume
        configMap:
          name: toxiproxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: toxiproxy
  namespace: tyk
spec:
  selector:
    app: toxiproxy
  ports:
  - name: dashboard
    port: 3000
    targetPort: dashboard
  - name: cp-gateway
    port: 8080
    targetPort: cp-gateway
  - name: dp-gateway
    port: 8081
    targetPort: dp-gateway
  - name: mdcb
    port: 9091
    targetPort: mdcb
  - name: redis-cp
    port: 6379
    targetPort: redis-cp
  - name: redis-dp
    port: 8379
    targetPort: redis-dp
  - name: mongo
    port: 27017
    targetPort: mongo
  - name: api
    port: 8474
    targetPort: api
  type: ClusterIP