version: "3.9"
services:
  tyk:
    container_name: tyk
    image: ${tyk_image}
    env_file:
      - tyk.env
    volumes:
      # - ${certs_dir}:/etc/ssl/certs
      - gw_certs_volume:/etc/ssl/certs/
      - confs_volume:/conf/
    ports:
      - "6000:6000"
      - "8003:8003"
      - "8080:8080"
    entrypoint: ["/bin/bash"]
    command:
      - "-c"
      - |
        update-ca-certificates
        /opt/tyk-gateway/tyk --conf /conf/tyk.conf

  tyk-analytics:
    container_name: tyk-analytics
    image: ${tyk_analytics_image}
    volumes:
      - confs_volume:/conf/
    ports:
      - "3000:3000"
      - "5000:5000"
      - "1026:1025"
    env_file:
      - tyk-analytics.env
    command: [ "--conf", "/conf/tyk-analytics.conf" ]


  tyk-pump:
    container_name: tyk-pump
    image: ${tyk_pump_image}
    volumes:
      - confs_volume:/conf
    ports:    
      - "8061:8061"
    env_file:
      - tyk-pump.env
    command: [ "--conf", "/conf/tyk-pump.conf" ]

  tyk-sink:
    container_name: tyk-sink
    image: ${tyk_sink_image}
    ports:
    - "9090:9090"
    env_file:
      - tyk-sink.env

volumes:
  confs_volume:
    external: true
  gw_certs_volume:
    external: true
