version: "3.9"
services:
  redis-datacenter-1:
    container_name: redis-datacenter-1
    image: ${REDIS_IMAGE}
    ports:
      - "6381:6379"
    env_file:
      - ../configsets/${CONFIGSET}/redis.env

  redis-datacenter-2:
    container_name: redis-datacenter-2
    image: ${REDIS_IMAGE}
    ports:
      - "6382:6379"
    env_file:
      - ../configsets/${CONFIGSET}/redis.env