version: "3.9"
services:
  redis:
    image: ${REDIS_IMAGE}
    env_file:
      - ../configsets/${CONFIGSET}/redis.env
    ports:
      - "6379:6379"
    # command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    # environment:
    #   - ALLOW_EMPTY_PASSWORD=yes

    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  mongo:
    image: ${MONGO_IMAGE}
    env_file:
      - ../configsets/${CONFIGSET}/mongo.env
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=123456789
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  default:
    name: tyk-network
    external: true