x-aws-vpc: ${AWS_VPC}

x-aws-cloudformation:
  Resources:
    LoadBalancer:
    MongoTCP27017Listener:
    MongoTCP27017TargetGroup:
    MongoService:
      DependsOn:
      Properties:
        LoadBalancers:
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
            Subnets:
              - subnet-04d34f3e5863af20a
              # - subnet-06ab6f58bb6d23123 public-1a
              # - subnet-0bbe276402b376013 public-1b
    RedisTCP6379Listener:
    RedisTCP6379TargetGroup:
    RedisService:
      DependsOn:
      Properties:
        LoadBalancers:
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: DISABLED
            Subnets:
              - subnet-04d34f3e5863af20a
              # - subnet-06ab6f58bb6d23123 public-1a
              # - subnet-0bbe276402b376013 public-1b
networks:
  default:
    name: tyk-network
    external: false