version: "3.9"
services:
  redis:
    image: ${REDIS_IMAGE}
    # extends: 
    #   file: docker-compose.volumes.yml
    #   service: redis
    ports:
      - "6379:6379"
    # command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  mongo:
    image: ${MONGO_IMAGE}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456789
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  default:
    name: tyk-network
    external: true