version: "3.9"
services:
  redis-datacenter-1:
    profiles: ["all", "slave-datacenter"]
    container_name: redis-datacenter-1
    image: ${REDIS_IMAGE}
    ports:
      - "6381:6379"
    env_file:
      - ../configsets/${CONFIGSET}/redis.env
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  redis-datacenter-2:
    profiles: ["all", "slave-datacenter"]
    container_name: redis-datacenter-2
    image: ${REDIS_IMAGE}
    ports:
      - "6382:6379"
    env_file:
      - ../configsets/${CONFIGSET}/redis.env
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s