version: "3.9"
services:
  upstream:
    image: citizenstig/httpbin
    restart: always

  gateway:
    image: ${REGISTRY}/${GW_IMAGE}
    ports:
      - "8080:8080"
    environment:
        - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=http://dashboard:3000
        - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=http://dashboard:3000
    volumes:
      - ../confs/${CONFIG}:/conf
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]
    healthcheck:
      # test: curl -s --fail http://localhost:8080/hello | grep -o '.*status":"pass".*dashboard":{"status":"pass".*redis":{"status":"pass"'
      # interval: 5s
      # retries: 10
      # start_period: 5s
      # timeout: 10s

  dashboard:
    image: ${REGISTRY}/${DB_IMAGE}
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - TYK_LOGLEVEL=${TYK_LOGLEVEL:-debug}
      - TYK_DB_LICENSEKEY=${TYK_DB_LICENSE}
    volumes:
      - ../confs/${CONFIG}:/conf
    entrypoint: ["/opt/tyk-dashboard/tyk-analytics", "--conf", "/conf/tyk-analytics.conf"]

  pump:
    image: ${REGISTRY}/${PUMP_IMAGE}
    volumes:
      - ../confs/${CONFIG}:/conf
      - /tmp/pump-data:/pump-data
    depends_on:
      - gateway
    entrypoint: ["/opt/tyk-pump/tyk-pump", "--conf", "/conf/tyk-pump.conf"]  

networks:
  default:
    name: tyk-network
    external: true