version: "3.9"
services:
  upstream:
    image: citizenstig/httpbin
    restart: always

  gateway:
    image: ${REGISTRY}/${GWIMAGE}
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    ports:
      - "8080:8080"
    volumes:
      - ../confs/${CONFIG}:/conf
    depends_on:
      - redis
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]

  fileserver:
    image: nginx
    volumes:
      - /Users/kiki/Github/internal-auth:/usr/share/nginx/html
    ports:
    - "9999:80"
  
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"