services:
  upstream:
    image: citizenstig/httpbin

  dashboard:
    image: ${REGISTRY}/${DBIMAGE}
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - TYK_LOGLEVEL=${TYK_LOGLEVEL:-debug}
      - TYK_DB_LICENSEKEY=${TYK_DB_LICENSE}
    volumes:
      - ../confs/${CONFIG}:/conf
    depends_on:
      - mongo
      - redis
    entrypoint: ["/opt/tyk-dashboard/tyk-analytics", "--conf", "/conf/tyk-analytics.conf"]

  gateway:
    image: ${REGISTRY}/${GWIMAGE}
    ports:
      - "8080:8080"
    environment:
        - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=http://dashboard:3000
        - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=http://dashboard:3000
    volumes:
      - ../confs/${CONFIG}:/conf
    depends_on:
      - redis
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]

  pump:
    image: ${REGISTRY}/${PUMPIMAGE}
    volumes:
      - ../confs/${CONFIG}:/conf
    depends_on:
      - gateway
      - mongo
    entrypoint: ["/opt/tyk-pump/tyk-pump", "--conf", "/conf/tyk-pump.conf"]

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
