services:
  upstream:
    image: citizenstig/httpbin
    restart: always

  mdcb: 
    image: tykio/${MDCBIMAGE}
    ports:
    - "9090:9090"
    environment:
    - TYK_MDCB_LICENSE=${TYK_MDCB_LICENSE}
    volumes: 
    - ../confs/${CONFIG}/tyk-sink.conf:/opt/tyk-sink/tyk_sink.conf
    depends_on:
    - redis
    - mongo
    - gateway

  gateway-datacenter:
    image: 754489498669.dkr.ecr.eu-central-1.amazonaws.com/tyk:master
    ports:
      - "8082:8082"
    environment:
      - TYK_LOGLEVEL=info
    volumes:
      - ../confs/${CONFIG}:/conf
    depends_on:
      - redis-datacenter
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk-gw-datacenter.conf"]
    healthcheck:
      test: curl -s --fail http://localhost:8082/hello | grep -o '.*status":"pass".*redis":{"status":"pass".*rpc":{"status":"pass"'
      interval: 5s
      retries: 10
      start_period: 4s
      timeout: 10s

  redis-datacenter:
    image: redis:6.2
    ports:
      - "6380:6379"
    environment:
      - loglevel=warning
    volumes:
      - ../data/${CONFIG}/redis-volumes/datacenter:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  dashboard:
    image: ${REGISTRY}/${DBIMAGE}
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - TYK_LOGLEVEL=${TYK_LOGLEVEL:-debug}
      - TYK_DB_LICENSEKEY=${TYK_DB_LICENSE}
    volumes:
      - ../confs/${CONFIG}:/conf
    depends_on:
      - mongo
      - redis
    entrypoint: ["/opt/tyk-dashboard/tyk-analytics", "--conf", "/conf/tyk-analytics.conf"]

  gateway:
    image: ${REGISTRY}/${GWIMAGE}
    ports:
      - "8080:8080"
    environment:
        - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=http://dashboard:3000
        - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=http://dashboard:3000
    volumes:
      - ../confs/${CONFIG}:/conf
    depends_on:
      - redis
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]
    healthcheck:
      test: curl -s --fail http://localhost:8080/hello | grep -o '.*status":"pass".*dashboard":{"status":"pass".*redis":{"status":"pass"'
      interval: 5s
      retries: 10
      start_period: 4s
      timeout: 10s

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - ../data/${CONFIG}/redis-volumes/master:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ../data/${CONFIG}/mongo-volume:/data/db

  pump:
    image: ${REGISTRY}/${PUMPIMAGE}
    volumes:
      - ../confs/${CONFIG}:/conf
      - /tmp/pump-data:/pump-data
    depends_on:
      - gateway
      - mongo
    entrypoint: ["/opt/tyk-pump/tyk-pump", "--conf", "/conf/tyk-pump.conf"]

  wait:
    image: hello-world:linux
    depends_on:
        redis-datacenter:
            condition: service_healthy
        redis:
            condition: service_healthy
        gateway:
            condition: service_healthy
        gateway-datacenter:
            condition: service_healthy
