services:
  upstream:
    image: citizenstig/httpbin
    restart: always

  mdcb: 
    image: tykio/tyk-mdcb-docker:v1.8.1
    ports:
    - "9090:9090"
    environment:
    - TYK_MDCB_LICENSE=${MDCB_LICENSE}
    volumes: 
    - ../confs/${ENV}-${CONFIG}/tyk-sink.conf:/opt/tyk-sink/tyk_sink.conf
    depends_on:
    - redis
    - mongo
    - gateway

  gateway-datacenter:
    image: 754489498669.dkr.ecr.eu-central-1.amazonaws.com/tyk:master
    ports:
      - "8082:8082"
    environment:
      - TYK_LOGLEVEL=info
    volumes:
      - ../confs/${ENV}-${CONFIG}:/conf
    depends_on:
      - redis-datacenter
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk-gw-datacenter.conf"]

  redis-datacenter:
    image: redis:6.2
    ports:
      - "6380:6379"
    environment:
      - loglevel=warning
    volumes:
      - ../data/${ENV}-${CONFIG}/redis-volumes/datacenter:/data

  dashboard:
    image: 754489498669.dkr.ecr.eu-central-1.amazonaws.com/tyk-analytics:master
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      - TYK_LOGLEVEL=${TYK_LOGLEVEL:-debug}
      - TYK_DB_LICENSEKEY=${TYK_DB_LICENSE}
    volumes:
      - ../confs/${ENV}-${CONFIG}:/conf
    depends_on:
      - mongo
      - redis
    entrypoint: ["/opt/tyk-dashboard/tyk-analytics", "--conf", "/conf/tyk-analytics.conf"]

  gateway:
    image: 754489498669.dkr.ecr.eu-central-1.amazonaws.com/tyk:master
    ports:
      - "8080:8080"
    environment:
        - TYK_GW_DBAPPCONFOPTIONS_CONNECTIONSTRING=http://dashboard:3000
        - TYK_GW_POLICIES_POLICYCONNECTIONSTRING=http://dashboard:3000
    volumes:
      - ../confs/${ENV}-${CONFIG}:/conf
    depends_on:
      - redis
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - ../data/${ENV}-${CONFIG}/redis-volumes/master:/data    

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ../data/${ENV}-${CONFIG}/mongo-volume:/data/db
