openapi: 3.0.0
info:
    title: Petstore API
      version: 1.0.0
        x-go-module: github.com/myorg/petstore
        paths:
            /pets:
                  get:
                          operationId: listPets
                                responses:
                                          '200':
                                            description: List of petopenapi: 3.0.0
                                            info:
                                                title: Petstore API
                                                  version: 1.0.0
                                                    x-go-module: github.com/myorg/petstore
                                                    paths:
                                                        /pets:
                                                              get:
                                                                      operationId: listPets
                                                                            responses:
                                                                                      '200':
                                                                                        description: List of petopenapi: 3.0.0
                                                                                        info:
                                                                                            title: Petstore API
                                                                                              version: 1.0.0
                                                                                                x-go-module: github.com/myorg/petstore
                                                                                                paths:
                                                                                                    /pets:
                                                                                                          get:
                                                                                                                  operationId: listPets
                                                                                                                        responses:
                                                                                                                                  '200':
                                                                                                                                              description: List of petsss
