version: "3.9"
services:
  upstream:
    image: citizenstig/httpbin
    networks:
      - public
    restart: always

  gateway:
    image: ${REGISTRY}/${GWIMAGE}
    ports:
      - "8080:8080"
    volumes:
      - ../confs/${CONFIG}:/conf
    networks:
      - private
      - public
    depends_on:
      - redis
    entrypoint: ["/opt/tyk-gateway/tyk", "--conf", "/conf/tyk.conf"]

  redis:
    image: redis:6.0
    networks:
      - private
    ports:
      - "6379:6379"

  mongo:
    image: mongo:4.2
    networks:
      - private
    ports:
      - "27017:27017"

networks:
  private: {}
  public: {}