name: Release
on:
  pull_request:
  push:
    tags:
      - 'v*'
permissions:
  contents: read
jobs:
  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ secrets.PROBE_APP_ID }}
          private-key: ${{ secrets.PROBE_APP_PRIVATE_KEY }}
          owner: TykTechnologies

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: AUTO env
        run: tar -czf /tmp/auto-env.tgz . && mv /tmp/auto-env.tgz .
      - uses: softprops/action-gh-release@26994186c0ac3ef5cae75ac16aa32e8153525f77 # v1
        with:
          token: ${{ steps.app-token.outputs.token }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: release.md
          files: auto-env.tgz