name: Release
on:
  pull_request:
  push:
    tags:
      - 'v*'
jobs:
  release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: AUTO env
        run: tar czf auto-env.tgz .
      - uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: release.md
          files: auto-env.tgz