name: Test²
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    tags:
      - 'v*'
    branches:
      - master
      - release-*
env:
  VARIATION: test-variations
  BASE_REF: ${{startsWith(github.event_name, 'pull_request') && github.base_ref || github.ref_name}}
jobs:
  test-controller-api:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      envfiles: ${{ steps.params.outputs.envfiles }}
      pump: ${{ steps.params.outputs.pump }}
      sink: ${{ steps.params.outputs.sink }}
    steps:
      - name: set params
        id: params
        uses: TykTechnologies/github-actions/.github/actions/tests/test-controller@QA-1607_test_reusable_workflows
        with:
          variation: ${{ env.VARIATION }}
          base_ref: ${{ env.BASE_REF }}
          test_type: api
  api-tests:
    needs:
      - test-controller-api
    runs-on: ubuntu-latest-m-2
    env:
      XUNIT_REPORT_PATH: ${{ github.workspace}}/test-results.xml
      BASE_REF: master
    permissions:
      id-token: write # This is required for requesting the Github JWT
      contents: read # This is required for actions/checkout
    strategy:
      fail-fast: false
      matrix:
        envfiles: ${{ fromJson(needs.test-controller-api.outputs.envfiles) }}
        pump: ${{ fromJson(needs.test-controller-api.outputs.pump) }}
        sink: ${{ fromJson(needs.test-controller-api.outputs.sink) }}
        exclude:
          - pump: tykio/tyk-pump-docker-pub:v1.8
            sink: $ECR/tyk-sink:master
          - pump: $ECR/tyk-pump:master
            sink: tykio/tyk-mdcb-docker:v2.4
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
          role-session-name: cipush
          aws-region: eu-central-1
      - id: ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
      - name: Setup tmate session only in debug mode
        uses: mxschmitt/action-tmate@v3
        if: runner.debug == '1'
        with:
          detached: true
          limit-access-to-actor: true
          # Only ${{ github.actor }} has access
          # See https://github.com/mxschmitt/action-tmate#use-registered-public-ssh-keys
      - uses: actions/checkout@v4
        with:
          path: auto
          fetch-depth: 1
      - name: Checkout test code
        uses: TykTechnologies/github-actions/.github/actions/tests/choose-test-branch@QA-1607_test_reusable_workflows
        with:
          org_gh_token: ${{ secrets.ORG_GH_TOKEN }}
          test_folder: api
      - name: env up
        id: env_up
        uses: TykTechnologies/github-actions/.github/actions/tests/env-up@QA-1607_test_reusable_workflows
        with:
          base_ref: ${{ env.BASE_REF }}
          tags: ${{'754489498669.dkr.ecr.eu-central-1.amazonaws.com/tyk-ee:'}}${{env.BASE_REF}}
          github_token: ${{ secrets.ORG_GH_TOKEN }}
          pump-image: ${{ matrix.pump }}
          sink-image: ${{ matrix.sink }}
          TYK_DB_LICENSEKEY: ${{ secrets.DASH_LICENSE }}
          TYK_MDCB_LICENSE: ${{ secrets.MDCB_LICENSE }}
      - name: Run API tests
        id: test_execution
        uses: TykTechnologies/github-actions/.github/actions/tests/api-tests@QA-1607_test_reusable_workflows
        with:
          user_api_secret: ${{ steps.env_up.outputs.USER_API_SECRET}}
      - name: Reporting
        if: always()
        with:
          execution_status: ${{ steps.test_execution.outcome }}
        uses: TykTechnologies/github-actions/.github/actions/tests/reporting@QA-1607_test_reusable_workflows

  test-controller-ui:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    outputs:
      envfiles: ${{ steps.params.outputs.envfiles }}
      pump: ${{ steps.params.outputs.pump }}
      sink: ${{ steps.params.outputs.sink }}
    steps:
      - name: set params
        id: params
        uses: TykTechnologies/github-actions/.github/actions/tests/test-controller@QA-1607_test_reusable_workflows
        with:
          variation: ${{ env.VARIATION }}
          base_ref: ${{ env.BASE_REF }}
          test_type: ui
  ui-tests:
    needs:
      - test-controller-ui
    runs-on: ubuntu-latest-m-2
    env:
      XUNIT_REPORT_PATH: ${{ github.workspace}}/test-results.xml
      BASE_REF: master
      MATRIX: ${{ toJson(matrix) }}
    permissions:
      id-token: write # This is required for requesting the Github JWT
      contents: read # This is required for actions/checkout
    strategy:
      fail-fast: false
      matrix:
        envfiles: ${{ fromJson(needs.test-controller-ui.outputs.envfiles) }}
        pump: ${{ fromJson(needs.test-controller-ui.outputs.pump) }}
        sink: ${{ fromJson(needs.test-controller-ui.outputs.sink) }}
        exclude:
          - pump: tykio/tyk-pump-docker-pub:v1.8
            sink: $ECR/tyk-sink:master
          - pump: $ECR/tyk-pump:master
            sink: tykio/tyk-mdcb-docker:v2.4
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
          role-session-name: cipush
          aws-region: eu-central-1
      - id: ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
      - name: Setup tmate session only in debug mode
        uses: mxschmitt/action-tmate@v3
        if: runner.debug == '1'
        with:
          detached: true
          limit-access-to-actor: true
          # Only ${{ github.actor }} has access
          # See https://github.com/mxschmitt/action-tmate#use-registered-public-ssh-keys
      - uses: actions/checkout@v4
        with:
          path: auto
          fetch-depth: 1
      - name: env up
        id: env_up
        uses: TykTechnologies/github-actions/.github/actions/tests/env-up@QA-1607_test_reusable_workflows
        with:
          base_ref: ${{ env.BASE_REF }}
          tags: ${{'754489498669.dkr.ecr.eu-central-1.amazonaws.com/tyk-ee:'}}${{env.BASE_REF}}
          github_token: ${{ secrets.ORG_GH_TOKEN }}
          TYK_DB_LICENSEKEY: ${{ secrets.DASH_LICENSE }}
          TYK_MDCB_LICENSE: ${{ secrets.MDCB_LICENSE }}
      - name: Checkout test code
        uses: TykTechnologies/github-actions/.github/actions/tests/choose-test-branch@QA-1607_test_reusable_workflows
        with:
          org_gh_token: ${{ secrets.ORG_GH_TOKEN }}
          test_folder: ui
      - name: Fix private module deps
        env:
          TOKEN: '${{ secrets.ORG_GH_TOKEN }}'
        run: >
          git config --global url."https://${TOKEN}@github.com".insteadOf "https://github.com"
      - name: Execute UI tests
        uses: TykTechnologies/github-actions/.github/actions/tests/ui-tests@QA-1607_test_reusable_workflows
        id: test_execution
      - name: Upload report to S3
        if: failure() && steps.test_execution.outcome != 'success' && steps.env_up.outcome == 'success'
        uses: TykTechnologies/github-actions/.github/actions/tests/ui-tests-report@QA-1607_test_reusable_workflows
        with:
          aws_acces_key_id: ${{ secrets.UI_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.UI_AWS_SECRET_ACCESS_KEY }}
      - name: Reporting
        if: always()
        with:
          execution_status: ${{ steps.test_execution.outcome }}
        uses: TykTechnologies/github-actions/.github/actions/tests/reporting@QA-1607_test_reusable_workflows
  release:
    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest-m-2
    needs:
      - api-tests
      - ui-tests
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.ORG_GH_TOKEN }}
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: release.md
