name: Integration tests

on:
  pull_request:
  workflow_dispatch:
    inputs:
      tat-tests:
        description: Run these tests from tyk-automated-tests to run, added to the pytest command line
        type: string
        default: 'tests/dashboard_admin_api'
      tyk-version:
        description: ECR docker tag to use
        type: string
        default: master
      tyk-analytics-version:
        description: ECR docker tag to use
        type: string
        default: master
      tyk-pump-version:
        description: ECR docker tag to use
        type: string
        default: master
      tyk-sink-version:
        description: ECR docker tag to use
        type: string
        default: master
  workflow_call:
    inputs:
      tat-tests:
        description: Run these tests from tyk-automated-tests to run, added to the pytest command line
        type: string
        default: 'tests/dashboard_admin_api'
      tyk-version:
        description: ECR docker tag to use
        type: string
        default: master
      tyk-analytics-version:
        description: ECR docker tag to use
        type: string
        default: master
      tyk-pump-version:
        description: ECR docker tag to use
        type: string
        default: master
      tyk-sink-version:
        description: ECR docker tag to use
        type: string
        default: master

env:
  GOPRIVATE: github.com/TykTechnologies

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  ecr-login:
    name: ecr-passwd
    runs-on: ubuntu-latest
  
    outputs:
      aws-ecr-pass: ${{ steps.ecr-pass.outputs.ECR_PASS }}

    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
          role-session-name: cipush
          aws-region: eu-central-1

      - name: Get ecr password
        id: ecr-pass
        run: |
          echo "ECR_PASS=$(aws ecr get-login-password --region eu-central-1)" >> "$GITHUB_OUTPUT"

# The job id corresponds to the environment type that the tests will run on
  pro:
    name: tyk-automated-tests on Tyk Pro
    runs-on: ubuntu-latest
    needs: ecr-login
    container:
      image: 754489498669.dkr.ecr.eu-central-1.amazonaws.com/tyk-automated-tests:1.0.0-rc1
      credentials:
        username: AWS
        password: ${{ needs.ecr-login.outputs.aws-ecr-pass }}

    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::754489498669:role/ecr_rw_tyk
          role-session-name: cipush
          aws-region: eu-central-1

      - id: ecr
        uses: aws-actions/amazon-ecr-login@v1

      - uses: actions/checkout@v3

      - name: env up
        working-directory: auto
        run: |
          echo "registry=${{ steps.ecr.outputs.registry }}
          tyk_sink_image=\${registry}/tyk-sink:${{ inputs.tyk-sink-version || 'master' }}
          tyk_image=\${registry}/tyk:${{ inputs.tyk-version || 'master' }}
          tyk_analytics_image=\${registry}/tyk-analytics:${{ inputs.tyk-analytics-version || 'master' }}
          tyk_pump_image=\${registry}/tyk-pump:${{ inputs.tyk-pump-version || 'master' }}" > versions.env
          # bring up env
          cat versions.env
          confs_dir=./${{ github.job }} docker compose -f ${{ github.job }}.yml -f deps.yml --env-file versions.env --env-file tat.env up --quiet-pull -d

      - name: Docker ps
        shell: bash
        run: docker ps
  

      - name: Waiting for dashboard
        shell: bash
        run: |
          while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000/hello/)" != "200" ]]; do sleep 60 && echo "waiting for dashboard '$(date +"%T")'"; done
        timeout-minutes: 15    

      - name: Run pytest
        working-directory: /app
        run: |
          echo "This is home: $GITHUB_WORKSPACE"
          . $GITHUB_WORKSPACE/auto/test.env
          pytest ${{ inputs.tat-tests }}
